[tool.poetry]
name = "h5darkframes"
version = "0.1.5"
description = "python API for creating and using hdf5 darkframes libraries "
authors = [
	"Vincent Berenz <vberenz@tuebingen.mpg.de>",
]
packages = [
	 { include = "h5darkframes" },
] 
license = "BSD-3-Clause"
readme = "readme.md"
homepage = "https://github.com/MPI-IS/h5darkframes"
repository = "https://github.com/MPI-IS/h5darkframes"


[tool.poetry.dependencies]
python = ">=3.8,<4"
numpy = "^1.23.4"
alive-progress = "^2.4.1"
h5py = "^3.7.0"
toml = "^0.10.2"
opencv-python = "4.5.1.48"
pytest = "^7.1.3"
rich = "^12.6.0"

[tool.poetry.scripts]
darkframes-zwoasi-config = 'h5darkframes.main:asi_zwo_darkframes_config'
darkframes-zwoasi-library = 'h5darkframes.main:asi_zwo_darkframes_library'
darkframes-info = 'h5darkframes.main:darkframes_info'
darkframes-display = 'h5darkframes.main:darkframe_display'
darkframes-fuse = 'h5darkframes.main:fuse'
darkframes-neighbors = 'h5darkframes.main:darkframe_neighbors'
darkframes-validation = 'h5darkframes.main:darkframes_validation'
darkframes-perform = 'h5darkframes.main:darkframes_perform'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


