# pyproject.toml
[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "master_converter"
version = "3.0.4"
description = "A package for converting units"
readme = "README.md"
authors = [{ name = "Spyridon Coryell", email = "master_converter@protonmail.com" }]
license = { file = "LICENSE" }

[project.urls]
Homepage = "https://github.com/SmallCoder13/master-converter"
Issues = "https://github.com/SmallCoder13/master-converter/issues"
