[package]
name = "fuzzydate"
version = "0.3.0"
edition = "2021"

[lib]
name = "fuzzydate"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.38"
pyo3 = { version = "0.22.4", features = ["chrono"]}
log = "0.4.22"
