[tool.poetry]
name = "vod-highlighter"
version = "0.3.3-alpha.2"
description = "tool to generate clips from a video. (mainly twitch VODs)"
authors = ["porplax <saynemarsh9@gmail.com>"]
readme = "README.md"
packages = [{include = "highlighter"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.1.1"
typer = "^0.12.5"
opencv-python = "^4.10.0.84"
pillow = "^10.4.0"
vosk = "^0.3.45"
nicegui = "^2.3.0"
pycparser = "^2.22"

[tool.poetry.scripts]
vod-highlighter = 'highlighter:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
