[package]
name = "primitive-pal"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "primitive_pal"
crate-type = ["cdylib"]

[dependencies]
arrow = "53.0.0"
crossbeam-channel = "0.5.13"
log = "0.4.22"
parquet = "53.0.0"
pyo3 = "0.22.0"
pyo3-log = "0.11.0"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
