[tool.poetry]
name = "pyaaware"
version = "1.5.14"
description = "Aaware Python development libraries"
authors = ["Jason Calderwood <jason@aaware.com>"]
maintainers = ["Jason Calderwood <jason@aaware.com>"]
homepage = "https://aaware.com"
license = "GPL-3.0-only"
include = [
    "pyaaware/pyaaware.cpython-311-arm-linux-gnueabihf.so",
    "pyaaware/pyaaware.cpython-311-aarch64-linux-gnu.so",
    "pyaaware/pyaaware.cpython-311-x86_64-linux-gnu.so",
    "pyaaware/pyaaware.cpython-311-darwin.so"
]

[tool.poetry.dependencies]
python = "~3.11"
torch = "~2.2"

[tool.poetry.group.dev.dependencies]
h5py = "^3.12.1"
icecream = "^2.1.3"
mypy = "^1.11.2"
mypy-extensions = "^1.0.0"
pybind11 = "^2.13.6"
pytest = "^8.3.3"
tensorflow = "~2.16"
tf2onnx = "^1.16.1"

[tool.mypy]
ignore_missing_imports = true
python_version = "3.11"
strict_optional = false
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

[tool.pytest.ini_options]
log_file = "pytest.log"
log_file_level = "DEBUG"
testpaths = ["test"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
