[tool.poetry]
name = "andeplane-cognite-ai"
version = "0.4.10"
description = "A set of AI tools for working with Cognite Data Fusion in Python."
authors = ["Anders Hafreager <anders.hafreager@cognite.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "cognite"}]

[tool.poetry.dependencies]
python = ">=3.9"
regex = ">=2022.10.31"


[tool.poetry.group.dev.dependencies]
twine = "^4.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
