[tool.poetry]
name = "adsGenericFunctions"
version = "0.2.51"
description = "Generic functions"
authors = [
    "Olivier Sigur√© <olivier.sigure@alchimiedatasolutions.com>",
    "Matthieu Vannin <matthieu.vannin@alchimiedatasolutions.com>",
    "Antoine Ducoulombier <antoine.ducoulombier@alchimiedatasolutions.com>"
]
license = "MIT"
readme = "README.md"
packages = [
    { include = "adsGenericFunctions" }
]

[tool.poetry.dependencies]
python = "^3.09"
psycopg2-binary = "2.9.5"
python-http-client = "3.3.7"
sendgrid = "6.10.0"
starkbank-ecdsa = "2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

