
[project]
name = "airless-core"
version = "0.1.3.dev2"
description = "Airless is a package that aims to build a serverless and lightweight orchestration platform, creating workflows of multiple tasks being executed on FaaS platform"
readme = "README.md"
requires-python = ">=3.9"
dynamic = ["dependencies"]
license = {text = "MIT License"}

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/astercapital/airless"
"Bug Tracker" = "https://github.com/astercapital/airless/issues"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--capture=sys --cache-clear --disable-warnings --junitxml=pytest.xml --cov-report=xml:cov.xml --cov=airless"
testpaths = ["tests"]

[tool.setuptools.packages.find]
include = ["airless*"]

[tool.flake8]
# List of patterns to ignore
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "*.pyc",
    "*.egg-info",
    "*.egg",
    "temp"
]

# Ignore error max line length
ignore = ["E501"]

# Maximum allowed line length
max-line-length = 120

# Cyclomatic complexity threshold
max-complexity = 15
