[tool.poetry]
name = "hexproof"
version = "0.3.7"
description = "A comprehensive library of Magic the Gathering API utilities."
authors = ["Investigamer <hexproofsystems@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
keywords = ["hexproof", "mtg", "scryfall", "magic", "gathering", "api", "investigamer"]
classifiers = [
    # Development status
    "Development Status :: 4 - Beta",

    # License
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",

    # Audience and Purpose
    "Intended Audience :: Developers",
    "Topic :: Games/Entertainment :: Board Games",

    # Frameworks used
    "Framework :: Pydantic",

    # Supported Python versions
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]

[tool.poetry.urls]
Changelog = "https://github.com/Investigamer/hexproof/blob/main/CHANGELOG.md"
Discord = "https://discord.gg/magicproxies"
Issues = "https://github.com/Investigamer/hexproof/issues"
Source = "https://github.com/Investigamer/hexproof"
Sponsor = "https://patreon.com/mpcfill"

[[tool.poetry.packages]]
include = "hexproof"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
requests = "^2.31.0"
pydantic = ">=2.9.2"
PyYAML = ">=6.0.1"
tomlkit = ">=0.13.2"
tomli = ">=2.0.2"
loguru = "^0.7.2"
omnitils = "^1.4.3"
bs4 = "^0.0.2"

[tool.poetry.group.dev.dependencies]
mypy = "^1.9.0"
pytest = "^8.1.1"
commitizen = "^3.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.commitizen]
version = "0.3.7"
tag_format = "$major.$minor.$patch"
update_changelog_on_bump = true
version_files = [
    "pyproject.toml:version"
]

[tool.poetry.scripts]
hexproof = 'hexproof._cli:HexproofCLI'
