[tool.poetry]
name = "kbrainsdk"
version = "0.22.5"
description = "SDK for using KBRaiN tools"
authors = ["Daniel E Fredriksen <daniel.fredriksen@us.kbr.com>"]
license = "unlicensed"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
pandas = "^1.3.3"
ecdsa = "^0.18.0"
pyasn1 = "^0.5.1"
python-jose = "^3.3.0"
rsa = "^4.9"
cryptography = "^43.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest-cov = "^4.1.0"
pytest = "^8.1.1"