[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ayoomoney"
version = "1.2.2"
authors = [
  { name="LazyDeus", email="dimaprodeus@yandex.ru" },
  { name="fofmow", email="fofmow@gmail.com" },
]
description = "Простая синхронная/асинхронная библиотека для работы с API ЮMoney"
readme = "readme.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "httpx~=0.23.0",
    "pydantic~=2.0",
    "click~=8.1"
]

[project.urls]
"Homepage" = "https://github.com/Demetrous-fd/ayoomoney"
"Bug Tracker" = "https://github.com/Demetrous-fd/ayoomoney/issues"