
[build-system]
requires = ["setuptools>=61.0", "versioningit"]
build-backend = "setuptools.build_meta"


# ----------------------------------------- setuptools -------------------------------------------
[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true


# ----------------------------------------- Project Metadata -------------------------------------
#
[project]
version = "0.0.0.dev3"
name = "LicenseMan"
requires-python = ">=3.10"
dependencies = [
    "LoggerMan == 0.0.0.dev49",
    "PyLinks",
    "PkgData",
    "PySerials",
    "MDit == 0.0.0.dev20",
    "ExceptionMan == 0.0.0.dev20",
    "platformdirs >= 4.3, < 5",
]
